pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('/var/lib/jenkins/workspace/node/')
                sh 'npm install'
            }
        }
    }
}
